# Pandas_Accessing_data

**Method**
- df.loc[]

In [1]:
from datasets import load_dataset
import pandas as pd

raw =load_dataset('lukebarousse/data_jobs')
df = raw.copy()
df = df['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df.job_posted_date)
df.info()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

**df.loc[] Method**

In [2]:
df.iloc[10:25,1:5] # In this method we use to slice the column using numbers 1:5 , after slicing the rows 10:20
# what if the i don't know the column index

,job_title,job_location,job_via,job_schedule_type
10,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time
11,Data Engineer,"Colorado Springs, CO (+3 others)",via The Muse,Full-time
12,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship
13,Senior Data Engineer,"New York, NY",via LinkedIn,Full-time
14,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",via BeBee,Full-time
15,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work
16,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time
17,Data Science Team Lead,"Laurel, MD",via APL Careers - Johns Hopkins University App...,Full-time
18,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time
19,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time
20,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time
21,Stage - data scientist – génération ia de donn...,"Asnières-sur-Seine, France",via Jobijoba,Full-time
22,Data Engineer / Développeur·euse Big Data F/H,"Nantes, France",via LinkedIn,Full-time
23,"PhD position in computer science (NLP, finance)",Russia,via hh.ru,Full-time
24,Data Scientist (DataLab Team),Anywhere,via LinkedIn,Full-time

**df.loc[] Method**

In [3]:
df.loc[:,'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]